site_name: Diogo's Dev Wiki
site_description: Notas de programação e dados
site_url: https://diogo-costa-silva.github.io/dev-notes/

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      lang: pt
  - awesome-pages
  - section-index
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      locale: pt
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      title: Nesta página
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

repo_url: https://github.com/diogo-costa-silva/dev-notes
edit_uri: ""   # desativa o botão "Edit this page"

extra:
  homepage: https://diogo-costa-silva.github.io/dev-notes/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/diogo-costa-silva

nav:
  - Home: index.md
  - Data Analysis: data_analysis/index.md
  - Python: python/index.md
  - Node.js: node/index.md
  - macOS: macos/index.md
  - Git: git/index.md
  - AI Tools: ai_tools/index.md
