[project]
name = "dev-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs-material>=9.6.18",
    "pymdown-extensions>=10.16.1",
]
